/*
 Navicat Premium Data Transfer

 Source Server         : sky
 Source Server Type    : MySQL
 Source Server Version : 80033
 Source Host           : localhost:3306
 Source Schema         : web

 Target Server Type    : MySQL
 Target Server Version : 80033
 File Encoding         : 65001

 Date: 31/05/2024 09:53:53
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for film
-- ----------------------------
DROP TABLE IF EXISTS `film`;
CREATE TABLE `film`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '电影名称',
  `director` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '导演',
  `type` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '电影种类，逻辑外键',
  `language` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '语言',
  `score` double(10, 0) NULL DEFAULT NULL COMMENT '电影评分',
  `url` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '电影图片url',
  `description` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '电影描述',
  `video` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4' COMMENT '视频地址',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1015 CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of film
-- ----------------------------
INSERT INTO `film` VALUES (1, '技術サポート', 'Chen Rui', '战争', '俄语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'If it scares you, it might be a good thing to try. If the plan doesn’t work, change the plan, but never the goal.', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (2, '事務員', 'Che Ka Keung', '恐怖', '中文', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'In the Objects tab, you can use the List List, Detail Detail and ER Diagram ER Diagram buttons to change                ', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (3, 'Database manager', 'Tang Ka Man', '科幻', '德语', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'To successfully establish a new connection to local/remote server - no matter via SSL, SSH or HTTP, set                 ', 'https://www.bilibili.com/bangumi/play/ep744327?theme=movie&from_spmid=666.7.recommend.6');
INSERT INTO `film` VALUES (4, 'Pharmacist', 'Zhu Ziyi', '历史', '法语', 7, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'The Synchronize to Database function will give you a full picture of all database differences.', 'https://www.bilibili.com/bangumi/play/ep744327?theme=movie&from_spmid=666.7.recommend.6');
INSERT INTO `film` VALUES (5, 'アカウントマネージャー', 'Mo Chung Yin', '喜剧', '法语', 7, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2536783096%2C2316485913%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'It provides strong authentication and secure encrypted communications between two hosts, known as SSH                   ', 'https://www.bilibili.com/bangumi/play/ss47168?theme=movie&from_spmid=666.7.hotlist.1');
INSERT INTO `film` VALUES (6, 'Fashion designer', 'Fukuda Tsubasa', '随便', '中文', 10, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'What you get by achieving your goals is not as important as what you become by achieving your goals.', 'https://www.bilibili.com/bangumi/play/ep287966?theme=movie&from_spmid=666.7.recommend.3');
INSERT INTO `film` VALUES (7, 'Singer', 'Ma Shihan', '科幻', '法语', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'In the Objects tab, you can use the List List, Detail Detail and ER Diagram ER Diagram buttons to change                ', 'https://www.bilibili.com/bangumi/play/ep280975?theme=movie&from_spmid=666.7.recommend.7');
INSERT INTO `film` VALUES (8, 'Architect', 'Ryan Cox', '高兴', '西班牙语', 3, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'In the middle of winter I at last discovered that there was in me an invincible summer. You must be the                 ', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (9, 'Pharmacist', 'Ono Kenta', '爱情', '中文', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Navicat provides powerful tools for working with queries: Query Editor for editing the query text directly,             ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (10, 'Biochemist', 'Che Ching Wan', '恐怖', '日语', 10, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/f66ed3cd-b2f2-47ef-955a-54ab94083e1a.jpg', 'Actually it is just in an idea when feel oneself can achieve and cannot achieve.', 'https://www.bilibili.com/bangumi/play/ep287966?theme=movie&from_spmid=666.7.recommend.3');
INSERT INTO `film` VALUES (11, 'Mobile application developer', 'Jeffrey Castillo', '冒险', '德语', 8, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Navicat Monitor requires a repository to store alerts and metrics for historical analysis.                              ', 'https://www.bilibili.com/bangumi/play/ep744327?theme=movie&from_spmid=666.7.recommend.6');
INSERT INTO `film` VALUES (12, 'Pharmacist', 'Yeow Tsz Ching', '战争', '西班牙语', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Difficult circumstances serve as a textbook of life for people.', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (13, 'Graphic designer', 'Yau Ming Sze', '战争', '俄语', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'SQL Editor allows you to create and edit SQL text, prepare and execute selected queries.', 'https://www.bilibili.com/bangumi/play/ep287966?theme=movie&from_spmid=666.7.recommend.3');
INSERT INTO `film` VALUES (14, '歯科矯正医', 'Cai Xiuying', '历史', '德语', 7, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/f66ed3cd-b2f2-47ef-955a-54ab94083e1a.jpg', 'Anyone who has never made a mistake has never tried anything new. In a Telnet session, all communications,              ', 'https://www.bilibili.com/bangumi/play/ep313573?theme=movie&from_spmid=666.7.feed.1');
INSERT INTO `film` VALUES (15, 'げいにん', 'Barbara Richardson', '喜剧', '德语', 1, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'It collects process metrics such as CPU load, RAM usage, and a variety of other resources over SSH/SNMP.                ', 'https://www.bilibili.com/bangumi/play/ss42715?theme=movie&from_spmid=666.7.hotlist.4');
INSERT INTO `film` VALUES (16, '事務長', 'Tsui Tin Wing', '冒险', '中文', 7, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'You must be the change you wish to see in the world. Instead of wondering when your next vacation is,                   ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (17, 'Biochemist', 'Sato Sakura', '战争', '德语', 7, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'If the plan doesn’t work, change the plan, but never the goal. There is no way to happiness. Happiness is the way.    ', 'https://www.bilibili.com/bangumi/play/ep280975?theme=movie&from_spmid=666.7.recommend.7');
INSERT INTO `film` VALUES (18, 'Sales manager', 'Noguchi Takuya', '历史', '法语', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Navicat provides powerful tools for working with queries: Query Editor for editing the query text directly,             ', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (19, 'グラフィックデザイナー', 'Eddie Myers', '动作', '俄语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'Navicat allows you to transfer data from one database and/or schema to another with detailed analytical process.', 'https://www.bilibili.com/bangumi/play/ep313573?theme=movie&from_spmid=666.7.feed.1');
INSERT INTO `film` VALUES (20, 'Marketing director', 'Nakajima Kenta', '随便', '法语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Monitored servers include MySQL, MariaDB and SQL Server, and compatible with cloud databases like Amazon                ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (21, '人事マネージャー', 'Chris Olson', '随便', '西班牙语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D3956236579%2C2419653314%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'It is used while your ISPs do not allow direct connections, but allows establishing HTTP connections.', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (22, 'Food scientist', 'Leung Hok Yau', '战争', '中文', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Navicat provides a wide range advanced features, such as compelling code editing capabilities, smart                    ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (23, 'Horticulturist', 'Justin Ford', '高兴', '德语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'You will succeed because most people are lazy. It provides strong authentication and secure encrypted                   ', 'https://www.bilibili.com/bangumi/play/ss47168?theme=movie&from_spmid=666.7.hotlist.1');
INSERT INTO `film` VALUES (24, 'Business reporter', 'Brian Reed', '动作', '德语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/f66ed3cd-b2f2-47ef-955a-54ab94083e1a.jpg', 'The reason why a great man is great is that he resolves to be a great man.', 'https://www.bilibili.com/bangumi/play/ep287966?theme=movie&from_spmid=666.7.recommend.3');
INSERT INTO `film` VALUES (25, 'Insurance sales agent', 'Xiao Lan', '战争', '俄语', 8, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2536783096%2C2316485913%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'If the plan doesn’t work, change the plan, but never the goal. After logged in the Navicat Cloud feature,             ', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (26, 'Office manager', 'Bobby Hicks', '随便', '英语', 8, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'Anyone who has never made a mistake has never tried anything new. If you wait, all that happens is you get older.', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (27, '情報セキュリティアナリスト', 'Chiba Kenta', '动作', '法语', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Navicat Monitor is a safe, simple and agentless remote server monitoring tool that is packed with powerful              ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (28, 'Makeup artist', 'Sato Tsubasa', '随便', '德语', 3, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Navicat Monitor can be installed on any local computer or virtual machine and does not require any software             ', 'https://www.bilibili.com/bangumi/play/ep313573?theme=movie&from_spmid=666.7.feed.1');
INSERT INTO `film` VALUES (29, 'かんさやく', 'Miguel Ross', '科幻', '英语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'To open a query using an external editor, control-click it and select Open with External Editor. You                    ', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (30, 'マルチメディアアニメーター', 'Hara Daisuke', '历史', '英语', 8, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'The Navigation pane employs tree structure which allows you to take action upon the database and their                  ', 'https://www.bilibili.com/bangumi/play/ss42715?theme=movie&from_spmid=666.7.hotlist.4');
INSERT INTO `film` VALUES (31, 'Veterinarian', 'Lok Sum Wing', '动作', '俄语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D3956236579%2C2419653314%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Actually it is just in an idea when feel oneself can achieve and cannot achieve.', 'https://www.bilibili.com/bangumi/play/ep313573?theme=movie&from_spmid=666.7.feed.1');
INSERT INTO `film` VALUES (32, 'Chief operations officer', 'Ku Wing Fat', '高兴', '英语', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Navicat provides powerful tools for working with queries: Query Editor for editing the query text directly,             ', 'https://www.bilibili.com/bangumi/play/ep384789?theme=movie&from_spmid=666.7.recommend.2');
INSERT INTO `film` VALUES (33, 'Auditor', 'Ying Siu Wai', '动作', '西班牙语', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your                  ', 'https://www.bilibili.com/bangumi/play/ss46617?theme=movie&from_spmid=666.7.hotlist.5');
INSERT INTO `film` VALUES (34, 'Biochemist', 'Feng Shihan', '动作', '俄语', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'It collects process metrics such as CPU load, RAM usage, and a variety of other resources over SSH/SNMP.                ', 'https://www.bilibili.com/bangumi/play/ep313573?theme=movie&from_spmid=666.7.feed.1');
INSERT INTO `film` VALUES (35, 'Horticulturist', 'Sasaki Seiko', '高兴', '俄语', 3, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'The Information Pane shows the detailed object information, project activities, the DDL of database objects,            ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (36, '生化学者', 'Kojima Ayato', '高兴', '俄语', 7, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'To clear or reload various internal caches, flush tables, or acquire locks, control-click your connection               ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (37, 'Dentist', 'Lei Lu', '科幻', '法语', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/f66ed3cd-b2f2-47ef-955a-54ab94083e1a.jpg', 'It is used while your ISPs do not allow direct connections, but allows establishing HTTP connections.', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (38, 'UX/UI designer', 'Nomura Riku', '喜剧', '日语', 0, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'The On Startup feature allows you to control what tabs appear when you launch Navicat.', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (39, 'マーケティング部長', 'Ng Tsz Ching', '随便', '俄语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'To successfully establish a new connection to local/remote server - no matter via SSL or SSH, set the                   ', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (40, 'Makeup artist', 'Cai Anqi', '爱情', '中文', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2536783096%2C2316485913%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Sometimes you win, sometimes you learn. Export Wizard allows you to export data from tables, collections,               ', 'https://www.bilibili.com/bangumi/play/ss46617?theme=movie&from_spmid=666.7.hotlist.5');
INSERT INTO `film` VALUES (41, 'Personal trainer', 'Sugawara Rin', '冒险', '英语', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'A man’s best friends are his ten fingers. To clear or reload various internal caches, flush tables,                   ', 'https://www.bilibili.com/bangumi/play/ss42715?theme=movie&from_spmid=666.7.hotlist.4');
INSERT INTO `film` VALUES (42, 'Orthodontist', 'Ti Fat', '高兴', '德语', 1, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'A query is used to extract data from the database in a readable format according to the user\'s request.                 ', 'https://www.bilibili.com/bangumi/play/ss47168?theme=movie&from_spmid=666.7.hotlist.1');
INSERT INTO `film` VALUES (43, 'Veterinarian', 'James Hunt', '历史', '英语', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Optimism is the one quality more associated with success and happiness than any other.', 'https://www.bilibili.com/bangumi/play/ss47168?theme=movie&from_spmid=666.7.hotlist.1');
INSERT INTO `film` VALUES (44, '獣医助手', 'Francis Brooks', '动作', '法语', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'What you get by achieving your goals is not as important as what you become by achieving your goals.', 'https://www.bilibili.com/bangumi/play/ep280975?theme=movie&from_spmid=666.7.recommend.7');
INSERT INTO `film` VALUES (45, 'Professor', 'David Soto', '恐怖', '英语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'All journeys have secret destinations of which the traveler is unaware.', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (46, 'メイクアップアーティスト', 'Siu Sai Wing', '高兴', '德语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2536783096%2C2316485913%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'To start working with your server in Navicat, you should first establish a connection or several connections            ', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (47, 'Biochemist', 'Wu Xiaoming', '动作', '德语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'The repository database can be an existing MySQL, MariaDB, PostgreSQL, SQL Server, or Amazon RDS instance.', 'https://www.bilibili.com/bangumi/play/ss47168?theme=movie&from_spmid=666.7.hotlist.1');
INSERT INTO `film` VALUES (48, 'Office clerk', 'Okamoto Ayato', '历史', '日语', 3, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'Anyone who has ever made anything of importance was disciplined. Export Wizard allows you to export data                ', 'https://www.bilibili.com/bangumi/play/ep384789?theme=movie&from_spmid=666.7.recommend.2');
INSERT INTO `film` VALUES (49, 'マルチメディアアニメーター', 'Lo Wing Fat', '随便', '中文', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your                  ', 'https://www.bilibili.com/bangumi/play/ep313573?theme=movie&from_spmid=666.7.feed.1');
INSERT INTO `film` VALUES (50, 'Producer', 'Mok Tin Wing', '恐怖', '英语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'If your Internet Service Provider (ISP) does not provide direct access to its server, Secure Tunneling                  ', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (51, 'アカウントマネージャー', 'Pan Xiuying', '恐怖', '德语', 8, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Genius is an infinite capacity for taking pains. Navicat Data Modeler is a powerful and cost-effective                  ', 'https://www.bilibili.com/bangumi/play/ep384789?theme=movie&from_spmid=666.7.recommend.2');
INSERT INTO `film` VALUES (52, 'バーバー', 'Fung Kwok Ming', '爱情', '英语', 10, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2536783096%2C2316485913%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Monitored servers include MySQL, MariaDB and SQL Server, and compatible with cloud databases like Amazon                ', 'https://www.bilibili.com/bangumi/play/ep287966?theme=movie&from_spmid=666.7.recommend.3');
INSERT INTO `film` VALUES (53, '園芸家', 'Nishimura Mai', '爱情', '德语', 0, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'Remember that failure is an event, not a person. Monitored servers include MySQL, MariaDB and SQL Server,               ', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (54, 'グルーマー', 'Ikeda Yuto', '恐怖', '日语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'If opportunity doesn’t knock, build a door. Remember that failure is an event, not a person.', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (55, 'アカウントコーディネーター', 'Nicole Castillo', '动作', '西班牙语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'In the middle of winter I at last discovered that there was in me an invincible summer.', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (56, 'モバイルアプリケーション開発者', 'Yuen Lik Sun', '动作', '英语', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet.                            ', 'https://www.bilibili.com/bangumi/play/ep287966?theme=movie&from_spmid=666.7.recommend.3');
INSERT INTO `film` VALUES (57, 'Pharmacist', 'Anita Wells', '动作', '中文', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'All the Navicat Cloud objects are located under different projects. You can share the project to other                  ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (58, '人事マネージャー', 'Yoshida Mai', '爱情', '西班牙语', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2536783096%2C2316485913%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Always keep your eyes open. Keep watching. Because whatever you see can inspire you. The past has no                    ', 'https://www.bilibili.com/bangumi/play/ep384789?theme=movie&from_spmid=666.7.recommend.2');
INSERT INTO `film` VALUES (59, 'Biochemist', 'Kimberly Gonzales', '恐怖', '德语', 3, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'To clear or reload various internal caches, flush tables, or acquire locks, control-click your connection               ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (60, 'Housekeeper', 'Hara Kaito', '历史', '中文', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'If the Show objects under schema in navigation pane option is checked at the Preferences window, all                    ', 'https://www.bilibili.com/bangumi/play/ss47168?theme=movie&from_spmid=666.7.hotlist.1');
INSERT INTO `film` VALUES (61, 'Personal trainer', 'Koyama Yamato', '动作', '中文', 3, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'Anyone who has never made a mistake has never tried anything new. All the Navicat Cloud objects are located             ', 'https://www.bilibili.com/bangumi/play/ep744327?theme=movie&from_spmid=666.7.recommend.6');
INSERT INTO `film` VALUES (62, '情報セキュリティアナリスト', 'Amber Henderson', '冒险', '西班牙语', 0, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D3956236579%2C2419653314%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'SQL Editor allows you to create and edit SQL text, prepare and execute selected queries.', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (63, 'Veterinarian', 'He Yuning', '科幻', '日语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'All the Navicat Cloud objects are located under different projects. You can share the project to other                  ', 'https://www.bilibili.com/bangumi/play/ep313573?theme=movie&from_spmid=666.7.feed.1');
INSERT INTO `film` VALUES (64, 'Farmer', 'Kwong Hiu Tung', '科幻', '英语', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'I will greet this day with love in my heart. If the Show objects under schema in navigation pane option                 ', 'https://www.bilibili.com/bangumi/play/ep384789?theme=movie&from_spmid=666.7.recommend.2');
INSERT INTO `film` VALUES (65, 'ファッションデザイナー', 'Susan Anderson', '动作', '德语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2536783096%2C2316485913%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'To successfully establish a new connection to local/remote server - no matter via SSL, SSH or HTTP, set                 ', 'https://www.bilibili.com/bangumi/play/ep744327?theme=movie&from_spmid=666.7.recommend.6');
INSERT INTO `film` VALUES (66, 'アクチュアリー', 'Stephen Mitchell', '恐怖', '英语', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/f66ed3cd-b2f2-47ef-955a-54ab94083e1a.jpg', 'A man’s best friends are his ten fingers. The Main Window consists of several toolbars and panes for                  ', 'https://www.bilibili.com/bangumi/play/ss46617?theme=movie&from_spmid=666.7.hotlist.5');
INSERT INTO `film` VALUES (67, 'Barber', 'Fung Sai Wing', '喜剧', '中文', 0, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/f66ed3cd-b2f2-47ef-955a-54ab94083e1a.jpg', 'Navicat Monitor can be installed on any local computer or virtual machine and does not require any software             ', 'https://www.bilibili.com/bangumi/play/ss46617?theme=movie&from_spmid=666.7.hotlist.5');
INSERT INTO `film` VALUES (68, 'グルーマー', 'Wu Zhiyuan', '爱情', '德语', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'It can also manage cloud databases such as Amazon Redshift, Amazon RDS, Alibaba Cloud. Features in Navicat              ', 'https://www.bilibili.com/bangumi/play/ep280975?theme=movie&from_spmid=666.7.recommend.7');
INSERT INTO `film` VALUES (69, '歯科医', 'Kong Zitao', '喜剧', '俄语', 8, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your                  ', 'https://www.bilibili.com/bangumi/play/ep313573?theme=movie&from_spmid=666.7.feed.1');
INSERT INTO `film` VALUES (70, 'Mobile application developer', 'Nomura Akina', '历史', '英语', 3, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Typically, it is employed as an encrypted version of Telnet. Remember that failure is an event, not a person.           ', 'https://www.bilibili.com/bangumi/play/ep744327?theme=movie&from_spmid=666.7.recommend.6');
INSERT INTO `film` VALUES (71, 'げいにん', 'To Wai Han', '喜剧', '中文', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'Navicat Monitor requires a repository to store alerts and metrics for historical analysis.                              ', 'https://www.bilibili.com/bangumi/play/ep313573?theme=movie&from_spmid=666.7.feed.1');
INSERT INTO `film` VALUES (72, 'Tutor', 'Takagi Miu', '战争', '西班牙语', 3, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/f66ed3cd-b2f2-47ef-955a-54ab94083e1a.jpg', 'SQL Editor allows you to create and edit SQL text, prepare and execute selected queries.', 'https://www.bilibili.com/bangumi/play/ep384789?theme=movie&from_spmid=666.7.recommend.2');
INSERT INTO `film` VALUES (73, 'Insurance sales agent', 'Kong On Kay', '科幻', '德语', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Typically, it is employed as an encrypted version of Telnet. Such sessions are also susceptible to session              ', 'https://www.bilibili.com/bangumi/play/ep280975?theme=movie&from_spmid=666.7.recommend.7');
INSERT INTO `film` VALUES (74, 'クライアントサービスマネージャー', 'Nomura Yamato', '喜剧', '日语', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'You cannot save people, you can just love them. To get a secure connection, the first thing you need                    ', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (75, 'Barber', 'Choi Yu Ling', '动作', '德语', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'The Navigation pane employs tree structure which allows you to take action upon the database and their                  ', 'https://www.bilibili.com/bangumi/play/ss42715?theme=movie&from_spmid=666.7.hotlist.4');
INSERT INTO `film` VALUES (76, 'さいこうしっこうせきにんしゃ', 'Murata Rin', '喜剧', '中文', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D3956236579%2C2419653314%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Navicat provides a wide range advanced features, such as compelling code editing capabilities, smart                    ', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (77, 'Biochemist', 'Francis Mendez', '高兴', '日语', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'In a Telnet session, all communications, including username and password, are transmitted in plain-text,                ', 'https://www.bilibili.com/bangumi/play/ep384789?theme=movie&from_spmid=666.7.recommend.2');
INSERT INTO `film` VALUES (78, 'ソフトウェア開発者', 'Barbara Marshall', '高兴', '法语', 9, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Monitored servers include MySQL, MariaDB and SQL Server, and compatible with cloud databases like Amazon                ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (79, 'さいこうしっこうせきにんしゃ', 'Hui Sze Yu', '动作', '俄语', 3, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'If the plan doesn’t work, change the plan, but never the goal. All journeys have secret destinations                  ', 'https://www.bilibili.com/bangumi/play/ep744327?theme=movie&from_spmid=666.7.recommend.6');
INSERT INTO `film` VALUES (80, 'プロデューサー', 'Chan Sai Wing', '恐怖', '中文', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D3956236579%2C2419653314%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Navicat is a multi-connections Database Administration tool allowing you to connect to MySQL, Oracle,                   ', 'https://www.bilibili.com/bangumi/play/ss46617?theme=movie&from_spmid=666.7.hotlist.5');
INSERT INTO `film` VALUES (81, '獣医助手', 'Abe Hina', '战争', '西班牙语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Navicat provides a wide range advanced features, such as compelling code editing capabilities, smart                    ', 'https://www.bilibili.com/bangumi/play/ss47168?theme=movie&from_spmid=666.7.hotlist.1');
INSERT INTO `film` VALUES (82, 'Chief operations officer', 'Hung Sze Kwan', '战争', '西班牙语', 1, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2536783096%2C2316485913%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'I will greet this day with love in my heart. You will succeed because most people are lazy.', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (83, 'Database manager', 'Sano Aoi', '冒险', '英语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2536783096%2C2316485913%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'To successfully establish a new connection to local/remote server - no matter via SSL, SSH or HTTP, set                 ', 'https://www.bilibili.com/bangumi/play/ss46617?theme=movie&from_spmid=666.7.hotlist.5');
INSERT INTO `film` VALUES (84, '保険販売代理', 'Thelma Patterson', '战争', '中文', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/f66ed3cd-b2f2-47ef-955a-54ab94083e1a.jpg', 'Typically, it is employed as an encrypted version of Telnet. If the plan doesn’t work, change the plan,               ', 'https://www.bilibili.com/bangumi/play/ep287966?theme=movie&from_spmid=666.7.recommend.3');
INSERT INTO `film` VALUES (85, 'Housekeeper', 'Au Chung Yin', '历史', '西班牙语', 0, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/f66ed3cd-b2f2-47ef-955a-54ab94083e1a.jpg', 'Navicat Monitor requires a repository to store alerts and metrics for historical analysis.', 'https://www.bilibili.com/bangumi/play/ep384789?theme=movie&from_spmid=666.7.recommend.2');
INSERT INTO `film` VALUES (86, 'Veterinary assistant', 'Yamazaki Aoshi', '动作', '法语', 1, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Import Wizard allows you to import data to tables/collections from CSV, TXT, XML, DBF and more.', 'https://www.bilibili.com/bangumi/play/ss46617?theme=movie&from_spmid=666.7.hotlist.5');
INSERT INTO `film` VALUES (87, 'Web developer', 'Ku Wai Han', '动作', '俄语', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Navicat Cloud provides a cloud service for synchronizing connections, queries, model files and virtual                  ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (88, 'Fashion designer', 'Uchida Kasumi', '随便', '德语', 1, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'The Synchronize to Database function will give you a full picture of all database differences.                          ', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (89, 'マーケティング部長', 'Tanaka Hina', '恐怖', '中文', 8, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'With its well-designed Graphical User Interface(GUI), Navicat lets you quickly and easily create, organize,             ', 'https://www.bilibili.com/bangumi/play/ep287966?theme=movie&from_spmid=666.7.recommend.3');
INSERT INTO `film` VALUES (90, 'Auditor', 'Hou Jiehong', '动作', '西班牙语', 1, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/download.jpg', 'Champions keep playing until they get it right. Navicat Cloud could not connect and access your databases.              ', 'https://www.bilibili.com/bangumi/play/ss42715?theme=movie&from_spmid=666.7.hotlist.4');
INSERT INTO `film` VALUES (91, 'Wedding planner', 'Fujiwara Ayano', '战争', '中文', 5, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'After comparing data, the window shows the number of records that will be inserted, updated or deleted in the target.', 'https://www.bilibili.com/bangumi/play/ep744327?theme=movie&from_spmid=666.7.recommend.6');
INSERT INTO `film` VALUES (92, 'Software developer', 'Saito Ikki', '冒险', '德语', 0, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'In other words, Navicat provides the ability for data in different databases and/or schemas to be kept                  ', 'https://www.bilibili.com/bangumi/play/ep402380?theme=movie&from_spmid=666.7.recommend.1');
INSERT INTO `film` VALUES (93, '建築家\n', 'Bradley Boyd', '科幻', '德语', 0, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D59350063%2C4184272751%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'To clear or reload various internal caches, flush tables, or acquire locks, control-click your connection               ', 'https://www.bilibili.com/bangumi/play/ep280975?theme=movie&from_spmid=666.7.recommend.7');
INSERT INTO `film` VALUES (94, 'Human resources manager', 'Hasegawa Hikaru', '随便', '西班牙语', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D569002542%2C3666021707%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Anyone who has ever made anything of importance was disciplined. Navicat Cloud could not connect and                    ', 'https://www.bilibili.com/bangumi/play/ss47168?theme=movie&from_spmid=666.7.hotlist.1');
INSERT INTO `film` VALUES (95, '生化学者', 'Yuen Siu Wai', '喜剧', '英语', 8, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D3956236579%2C2419653314%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'I may not have gone where I intended to go, but I think I have ended up where I needed to be.                           ', 'https://www.bilibili.com/bangumi/play/ep384789?theme=movie&from_spmid=666.7.recommend.2');
INSERT INTO `film` VALUES (96, 'Biochemist', 'Lu Xiuying', '战争', '英语', 1, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D304203075%2C3354732399%26fm%3D253%26app%3D120%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Secure SHell (SSH) is a program to log in into another computer over a network, execute commands on a                   ', 'https://www.bilibili.com/bangumi/play/ss47168?theme=movie&from_spmid=666.7.hotlist.1');
INSERT INTO `film` VALUES (97, 'Personal trainer', 'Tang Ziyi', '动作', '德语', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D2953358986%2C3006034053%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from.', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (98, 'Marketing director', 'Murakami Ryota', '高兴', '德语', 2, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D137989166%2C1725463295%26fm%3D253%26app%3D138%26size%3Dw931%26n%3D0%26f%3DJPEG%26fmt%3Dauto.webp', 'I will greet this day with love in my heart. Actually it is just in an idea when feel oneself can achieve               ', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (99, 'Breeder', 'Tam Chung Yin', '恐怖', '德语', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/u%3D3956236579%2C2419653314%26fm%3D253%26fmt%3Dauto%26app%3D120%26f%3DJPEG.webp', 'Navicat Data Modeler is a powerful and cost-effective database design tool which helps you build high-quality           ', 'https://www.bilibili.com/bangumi/play/ep366580?theme=movie&from_spmid=666.7.recommend.4');
INSERT INTO `film` VALUES (100, '先生', 'Doris Wallace', '动作', '日语', 8, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', 'Anyone who has ever made anything of importance was disciplined. Always keep your eyes open. Keep watching.             ', 'https://www.bilibili.com/bangumi/play/ep744327?theme=movie&from_spmid=666.7.recommend.6');
INSERT INTO `film` VALUES (1019, 'test', 't', '爱情', 't', 6, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/e2435cce-1a5f-48d0-a8ce-0bfbb6546324tmp', 't', 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/videoDefault.mp4');
INSERT INTO `film` VALUES (1020, 'testt', 't', '喜剧', 't', 4, 'https://web-muelsyse.oss-cn-beijing.aliyuncs.com/dccea9de-dd58-4db4-b6f4-2868f80a000d.jpg', '2dw', 'https://www.bilibili.com/bangumi/play/ss46617?theme=movie');

-- ----------------------------
-- Table structure for news
-- ----------------------------
DROP TABLE IF EXISTS `news`;
CREATE TABLE `news`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `title` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '标题',
  `author` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '作者',
  `date` date NULL DEFAULT NULL COMMENT '时间',
  `description` varchar(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '正文',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 16 CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of news
-- ----------------------------
INSERT INTO `news` VALUES (1, 'To clear or reload various internal caches, flush tables,             ', 'Nakagawa Shino', '2018-05-07', 'After logged in the Navicat Cloud feature, the Navigation pane will be divided into Navicat Cloud and My Connections sections.                        ');
INSERT INTO `news` VALUES (2, 'In the Objects tab, you can use the List List, Detail                 ', 'Tian Lan', '2013-01-11', 'All the Navicat Cloud objects are located under different projects. You can share the project to other Navicat Cloud accounts for collaboration.');
INSERT INTO `news` VALUES (3, 'In the Objects tab, you can use the List List, Detail                 ', 'Takagi Minato', '2015-01-26', 'A man’s best friends are his ten fingers. A query is used to extract data from the database in a readable format according to the user\'s request.');
INSERT INTO `news` VALUES (4, 'Navicat allows you to transfer data from one database                 ', 'Shi Yunxi', '2003-06-07', 'Remember that failure is an event, not a person. You can select any connections, objects or projects, and then select the corresponding               ');
INSERT INTO `news` VALUES (5, 'Success consists of going from failure to failure without             ', 'Bernard Soto', '2012-01-15', 'Success consists of going from failure to failure without loss of enthusiasm. Secure Sockets Layer(SSL) is a protocol for transmitting                ');
INSERT INTO `news` VALUES (6, 'SQL Editor allows you to create and edit SQL text,                    ', 'Watanabe Ren', '2015-11-19', 'To open a query using an external editor, control-click it and select Open with External Editor. You can set the file path of an external             ');
INSERT INTO `news` VALUES (7, 'It is used while your ISPs do not allow direct connections,           ', 'Martha Nguyen', '2008-12-24', 'Typically, it is employed as an encrypted version of Telnet. Navicat Monitor is a safe, simple and agentless remote server monitoring                 ');
INSERT INTO `news` VALUES (8, 'To successfully establish a new connection to local/remote            ', 'To Wing Suen', '2016-04-18', 'Monitored servers include MySQL, MariaDB and SQL Server, and compatible with cloud databases like Amazon RDS, Amazon Aurora, Oracle                   ');
INSERT INTO `news` VALUES (9, 'If the Show objects under schema in navigation pane                   ', 'Mori Yuna', '2023-12-01', 'Navicat 15 has added support for the system-wide dark mode.');
INSERT INTO `news` VALUES (10, 'Champions keep playing until they get it right.', 'Kwong Tsz Hin', '2013-12-07', 'The On Startup feature allows you to control what tabs appear when you launch Navicat. Instead of wondering when your next vacation                   ');
INSERT INTO `news` VALUES (11, 'Anyone who has never made a mistake has never tried anything new.', 'Douglas Bell', '2016-07-21', 'After logged in the Navicat Cloud feature, the Navigation pane will be divided into Navicat Cloud and My Connections sections.');
INSERT INTO `news` VALUES (12, 'It is used while your ISPs do not allow direct connections,           ', 'Long Xiaoming', '2010-04-03', 'Import Wizard allows you to import data to tables/collections from CSV, TXT, XML, DBF and more. Navicat Monitor can be installed on                   ');
INSERT INTO `news` VALUES (13, 'With its well-designed Graphical User Interface(GUI),                 ', 'Kathleen Silva', '2024-05-21', 'All journeys have secret destinations of which the traveler is unaware.');
INSERT INTO `news` VALUES (14, 'To connect to a database or schema, simply double-click               ', 'Sit Fat', '2023-03-05', 'If you wait, all that happens is you get older. Flexible settings enable you to set up a custom key for comparison and synchronization.');
INSERT INTO `news` VALUES (15, 'All journeys have secret destinations of which the                    ', 'Hou Rui', '2005-12-11', 'To open a query using an external editor, control-click it and select Open with External Editor. You can set the file path of an external             ');
INSERT INTO `news` VALUES (16, 'Flexible settings enable you to set up a custom key                   ', 'Michael Rodriguez', '2021-11-22', 'The reason why a great man is great is that he resolves to be a great man. What you get by achieving your goals is not as important                   ');
INSERT INTO `news` VALUES (17, 'Navicat Cloud provides a cloud service for synchronizing              ', 'Shing Wing Sze', '2004-12-27', 'Navicat is a multi-connections Database Administration tool allowing you to connect to MySQL, Oracle, PostgreSQL, SQLite, SQL Server,                 ');
INSERT INTO `news` VALUES (18, 'The first step is as good as half over.', 'Mui Kwok Wing', '2013-04-15', 'If the Show objects under schema in navigation pane option is checked at the Preferences window, all database objects are also displayed in the pane.');
INSERT INTO `news` VALUES (19, 'Actually it is just in an idea when feel oneself can                  ', 'Cho Chiu Wai', '2018-11-20', 'Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from. A comfort zone is                    ');
INSERT INTO `news` VALUES (20, 'If the plan doesn’t work, change the plan, but never the goal.', 'Nishimura Misaki', '2023-09-20', 'The reason why a great man is great is that he resolves to be a great man. To successfully establish a new connection to local/remote                 ');
INSERT INTO `news` VALUES (21, 'What you get by achieving your goals is not as important              ', 'Wu Ming', '2008-09-01', 'Navicat authorizes you to make connection to remote servers running on different platforms (i.e. Windows, macOS, Linux and UNIX), and                 ');
INSERT INTO `news` VALUES (22, 'Champions keep playing until they get it right.', 'Peggy Mitchell', '2007-08-16', 'Difficult circumstances serve as a textbook of life for people. If the Show objects under schema in navigation pane option is checked                 ');
INSERT INTO `news` VALUES (23, 'The Navigation pane employs tree structure which allows               ', 'Chu Ka Fai', '2021-02-26', 'The Navigation pane employs tree structure which allows you to take action upon the database and their objects through their pop-up                   ');
INSERT INTO `news` VALUES (24, 'Actually it is just in an idea when feel oneself can                  ', 'Mao Lu', '2006-08-01', 'I will greet this day with love in my heart. If the Show objects under schema in navigation pane option is checked at the Preferences                 ');
INSERT INTO `news` VALUES (25, 'Creativity is intelligence having fun.', 'Lam Hiu Tung', '2024-02-09', 'A comfort zone is a beautiful place, but nothing ever grows there. A query is used to extract data from the database in a readable                    ');
INSERT INTO `news` VALUES (26, 'The Information Pane shows the detailed object information,           ', 'Masuda Kasumi', '2010-03-20', 'To start working with your server in Navicat, you should first establish a connection or several connections using the Connection window.');
INSERT INTO `news` VALUES (27, 'The repository database can be an existing MySQL, MariaDB,            ', 'Paula Morris', '2022-10-17', 'Navicat Cloud provides a cloud service for synchronizing connections, queries, model files and virtual group information from Navicat,                ');
INSERT INTO `news` VALUES (28, 'The repository database can be an existing MySQL, MariaDB,            ', 'Jin Zhiyuan', '2020-05-11', 'Optimism is the one quality more associated with success and happiness than any other.');
INSERT INTO `news` VALUES (29, 'Import Wizard allows you to import data to tables/collections         ', 'Leslie Phillips', '2014-05-12', 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your connection settings, queries,                  ');
INSERT INTO `news` VALUES (30, 'Secure Sockets Layer(SSL) is a protocol for transmitting              ', 'Mui Ching Wan', '2010-11-09', 'Creativity is intelligence having fun. Monitored servers include MySQL, MariaDB and SQL Server, and compatible with cloud databases                   ');
INSERT INTO `news` VALUES (31, 'Difficult circumstances serve as a textbook of life for people.       ', 'Chan Chung Yin', '2015-07-21', 'Genius is an infinite capacity for taking pains. The Information Pane shows the detailed object information, project activities, the                  ');
INSERT INTO `news` VALUES (32, 'To get a secure connection, the first thing you need                  ', 'Han Shihan', '2019-03-14', 'To clear or reload various internal caches, flush tables, or acquire locks, control-click your connection in the Navigation pane and                  ');
INSERT INTO `news` VALUES (33, 'Navicat provides powerful tools for working with queries:             ', 'Kikuchi Tsubasa', '2014-06-25', 'Navicat provides powerful tools for working with queries: Query Editor for editing the query text directly, and Query Builder, Find                   ');
INSERT INTO `news` VALUES (34, 'Navicat Monitor requires a repository to store alerts                 ', 'Yan Yuning', '2011-12-10', 'All the Navicat Cloud objects are located under different projects. You can share the project to other Navicat Cloud accounts for collaboration.');
INSERT INTO `news` VALUES (35, 'In a Telnet session, all communications, including                    ', 'Travis Reynolds', '2004-12-28', 'In other words, Navicat provides the ability for data in different databases and/or schemas to be kept up-to-date so that each repository             ');
INSERT INTO `news` VALUES (36, 'There is no way to happiness. Happiness is the way.', 'Liao Wai Yee', '2015-08-24', 'Monitored servers include MySQL, MariaDB and SQL Server, and compatible with cloud databases like Amazon RDS, Amazon Aurora, Oracle                   ');
INSERT INTO `news` VALUES (37, 'Instead of wondering when your next vacation is, maybe                ', 'Nakajima Mio', '2000-07-31', 'To get a secure connection, the first thing you need to do is to install OpenSSL Library and download Database Source.');
INSERT INTO `news` VALUES (38, 'The Synchronize to Database function will give you                    ', 'James Young', '2007-10-12', 'The reason why a great man is great is that he resolves to be a great man. Monitored servers include MySQL, MariaDB and SQL Server,                   ');
INSERT INTO `news` VALUES (39, 'Always keep your eyes open. Keep watching. Because                    ', 'Koon Cho Yee', '2021-08-16', 'All the Navicat Cloud objects are located under different projects. You can share the project to other Navicat Cloud accounts for collaboration.');
INSERT INTO `news` VALUES (40, 'A comfort zone is a beautiful place, but nothing ever grows there.', 'Wong Tin Wing', '2008-02-10', 'Flexible settings enable you to set up a custom key for comparison and synchronization. A man is not old until regrets take the place of dreams.');
INSERT INTO `news` VALUES (41, 'A query is used to extract data from the database in                  ', 'Wong On Kay', '2004-06-22', 'Champions keep playing until they get it right. A comfort zone is a beautiful place, but nothing ever grows there. Navicat Cloud provides             ');
INSERT INTO `news` VALUES (42, 'The On Startup feature allows you to control what tabs                ', 'Hasegawa Ayato', '2024-05-01', 'Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet.');
INSERT INTO `news` VALUES (43, 'Export Wizard allows you to export data from tables,                  ', 'Ueno Rin', '2012-08-18', 'What you get by achieving your goals is not as important as what you become by achieving your goals.');
INSERT INTO `news` VALUES (44, 'All the Navicat Cloud objects are located under different             ', 'Jamie Alvarez', '2011-03-31', 'Genius is an infinite capacity for taking pains. Navicat provides a wide range advanced features, such as compelling code editing capabilities,       ');
INSERT INTO `news` VALUES (45, 'The Navigation pane employs tree structure which allows               ', 'Saito Sakura', '2023-08-20', 'Navicat Monitor requires a repository to store alerts and metrics for historical analysis. Navicat Monitor is a safe, simple and agentless            ');
INSERT INTO `news` VALUES (46, 'In the Objects tab, you can use the List List, Detail                 ', 'Shao Rui', '2013-08-10', 'If your Internet Service Provider (ISP) does not provide direct access to its server, Secure Tunneling Protocol (SSH) / HTTP is another solution.');
INSERT INTO `news` VALUES (47, 'You will succeed because most people are lazy.', 'Guo Lan', '2000-06-05', 'SSH serves to prevent such vulnerabilities and allows you to access a remote server\'s shell without compromising security.');
INSERT INTO `news` VALUES (48, 'The past has no power over the present moment.', 'Wang Lan', '2005-02-26', 'I may not have gone where I intended to go, but I think I have ended up where I needed to be. It provides strong authentication and                   ');
INSERT INTO `news` VALUES (49, 'All journeys have secret destinations of which the                    ', 'Takagi Sakura', '2002-05-07', 'Success consists of going from failure to failure without loss of enthusiasm. In the middle of winter I at last discovered that there                 ');
INSERT INTO `news` VALUES (50, 'Difficult circumstances serve as a textbook of life for people.', 'Carolyn Patel', '2014-07-13', 'To get a secure connection, the first thing you need to do is to install OpenSSL Library and download Database Source.');
INSERT INTO `news` VALUES (51, 'If the plan doesn’t work, change the plan, but never the goal.', 'Lui Wing Sze', '2023-02-15', 'A man’s best friends are his ten fingers. I may not have gone where I intended to go, but I think I have ended up where I needed to be.');
INSERT INTO `news` VALUES (52, 'To successfully establish a new connection to local/remote            ', 'Hung Sze Kwan', '2012-09-14', 'All journeys have secret destinations of which the traveler is unaware. I may not have gone where I intended to go, but I think I have                ');
INSERT INTO `news` VALUES (53, 'There is no way to happiness. Happiness is the way.', 'Ishikawa Miu', '2018-11-22', 'Navicat is a multi-connections Database Administration tool allowing you to connect to MySQL, Oracle, PostgreSQL, SQLite, SQL Server,                 ');
INSERT INTO `news` VALUES (54, 'To successfully establish a new connection to local/remote            ', 'Lam Fu Shing', '2012-01-30', 'To successfully establish a new connection to local/remote server - no matter via SSL, SSH or HTTP, set the database login information                ');
INSERT INTO `news` VALUES (55, 'Such sessions are also susceptible to session hijacking,              ', 'Debbie Rose', '2002-08-27', 'With its well-designed Graphical User Interface(GUI), Navicat lets you quickly and easily create, organize, access and share information              ');
INSERT INTO `news` VALUES (56, 'Navicat 15 has added support for the system-wide dark mode.', 'Xiong Xiaoming', '2006-07-10', 'In the middle of winter I at last discovered that there was in me an invincible summer. Actually it is just in an idea when feel oneself              ');
INSERT INTO `news` VALUES (57, 'To successfully establish a new connection to local/remote            ', 'Yamamoto Ayano', '2023-03-19', 'Anyone who has ever made anything of importance was disciplined. Always keep your eyes open. Keep watching. Because whatever you see can inspire you.');
INSERT INTO `news` VALUES (58, 'The Information Pane shows the detailed object information,           ', 'Ethel Scott', '2009-07-14', 'To open a query using an external editor, control-click it and select Open with External Editor. You can set the file path of an external             ');
INSERT INTO `news` VALUES (59, 'It provides strong authentication and secure encrypted                ', 'Brenda Soto', '2011-04-22', 'You will succeed because most people are lazy. After logged in the Navicat Cloud feature, the Navigation pane will be divided into                    ');
INSERT INTO `news` VALUES (60, 'It collects process metrics such as CPU load, RAM usage,              ', 'Shimizu Mai', '2018-05-02', 'Creativity is intelligence having fun. To successfully establish a new connection to local/remote server - no matter via SSL, SSH or                  ');
INSERT INTO `news` VALUES (61, 'Navicat is a multi-connections Database Administration                ', 'Yamazaki Momoe', '2019-09-11', 'Genius is an infinite capacity for taking pains. It wasn’t raining when Noah built the ark. Navicat Monitor is a safe, simple and                   ');
INSERT INTO `news` VALUES (62, 'Monitored servers include MySQL, MariaDB and SQL Server,              ', 'Liu Shihan', '2015-11-13', 'After logged in the Navicat Cloud feature, the Navigation pane will be divided into Navicat Cloud and My Connections sections.                        ');
INSERT INTO `news` VALUES (63, 'To connect to a database or schema, simply double-click               ', 'Xiong Xiaoming', '2002-03-03', 'Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet.');
INSERT INTO `news` VALUES (64, 'After comparing data, the window shows the number of                  ', 'Wong Ting Fung', '2023-04-18', 'Navicat Monitor is a safe, simple and agentless remote server monitoring tool that is packed with powerful features to make your monitoring           ');
INSERT INTO `news` VALUES (65, 'Navicat provides powerful tools for working with queries:             ', 'Tao Jiehong', '2014-01-31', 'It is used while your ISPs do not allow direct connections, but allows establishing HTTP connections. Anyone who has never made a mistake             ');
INSERT INTO `news` VALUES (66, 'Navicat Monitor requires a repository to store alerts                 ', 'Zhou Zhennan', '2017-05-23', 'The Navigation pane employs tree structure which allows you to take action upon the database and their objects through their pop-up                   ');
INSERT INTO `news` VALUES (67, 'It is used while your ISPs do not allow direct connections,           ', 'Sano Ayano', '2013-10-28', 'SSH serves to prevent such vulnerabilities and allows you to access a remote server\'s shell without compromising security.                            ');
INSERT INTO `news` VALUES (68, 'All journeys have secret destinations of which the                    ', 'Miguel Garza', '2022-03-23', 'Navicat Monitor can be installed on any local computer or virtual machine and does not require any software installation on the servers               ');
INSERT INTO `news` VALUES (69, 'If it scares you, it might be a good thing to try.', 'Au Yun Fat', '2023-02-18', 'Navicat Data Modeler is a powerful and cost-effective database design tool which helps you build high-quality conceptual, logical and                 ');
INSERT INTO `news` VALUES (70, 'A comfort zone is a beautiful place, but nothing ever grows there.', 'Fang Jiehong', '2000-10-26', 'Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from. The Information Pane                 ');
INSERT INTO `news` VALUES (71, 'The Synchronize to Database function will give you                    ', 'Cui Rui', '2003-08-27', 'The Synchronize to Database function will give you a full picture of all database differences.');
INSERT INTO `news` VALUES (72, 'Navicat provides a wide range advanced features, such                 ', 'Wong Yu Ling', '2008-09-16', 'Genius is an infinite capacity for taking pains. Flexible settings enable you to set up a custom key for comparison and synchronization.              ');
INSERT INTO `news` VALUES (73, 'The repository database can be an existing MySQL, MariaDB,            ', 'Yamada Riku', '2000-06-25', 'In the middle of winter I at last discovered that there was in me an invincible summer. The Navigation pane employs tree structure                    ');
INSERT INTO `news` VALUES (74, 'Navicat provides a wide range advanced features, such                 ', 'Hirano Yuito', '2012-04-25', 'Navicat Monitor can be installed on any local computer or virtual machine and does not require any software installation on the servers               ');
INSERT INTO `news` VALUES (75, 'I may not have gone where I intended to go, but I think               ', 'Clifford Murray', '2006-12-02', 'In the middle of winter I at last discovered that there was in me an invincible summer. It collects process metrics such as CPU load,                 ');
INSERT INTO `news` VALUES (76, 'In a Telnet session, all communications, including                    ', 'Takahashi Seiko', '2015-05-05', 'Navicat authorizes you to make connection to remote servers running on different platforms (i.e. Windows, macOS, Linux and UNIX), and                 ');
INSERT INTO `news` VALUES (77, 'Export Wizard allows you to export data from tables,                  ', 'Jane Walker', '2011-05-31', 'I may not have gone where I intended to go, but I think I have ended up where I needed to be. Navicat Data Modeler is a powerful and                  ');
INSERT INTO `news` VALUES (78, 'Flexible settings enable you to set up a custom key                   ', 'Cui Zhennan', '2006-11-05', 'Such sessions are also susceptible to session hijacking, where a malicious user takes over your session once you have authenticated.');
INSERT INTO `news` VALUES (79, 'Secure Sockets Layer(SSL) is a protocol for transmitting              ', 'Beverly Morgan', '2006-02-02', 'The past has no power over the present moment. Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet.');
INSERT INTO `news` VALUES (80, 'Anyone who has never made a mistake has never tried anything new.', 'Fu Rui', '2002-03-16', 'You cannot save people, you can just love them. The Main Window consists of several toolbars and panes for you to work on connections,                ');
INSERT INTO `news` VALUES (81, 'Navicat Data Modeler enables you to build high-quality                ', 'Peter Warren', '2021-12-05', 'Champions keep playing until they get it right. I may not have gone where I intended to go, but I think I have ended up where I needed to be.');
INSERT INTO `news` VALUES (82, 'The repository database can be an existing MySQL, MariaDB,            ', 'Wu Zhennan', '2018-02-26', 'Anyone who has ever made anything of importance was disciplined. To open a query using an external editor, control-click it and select                ');
INSERT INTO `news` VALUES (83, 'The Synchronize to D123213 will give you                    ', 'Chen Anqi', '2009-06-19', 'Anyone who has ever made anything of importance was disciplined. A man’s best friends are his ten fingers. You must be the change                   ');
INSERT INTO `news` VALUES (84, 'You will succeed because most people are lazy.', 'Mo Xiuying', '2010-04-30', 'I may not have gone where I intended to go, but I think I have ended up where I needed to be. The On Startup feature allows you to                    ');
INSERT INTO `news` VALUES (85, 'Import Wizard allows you to import data to tables/collections         ', 'Yung Chiu Wai', '2001-09-23', 'I destroy my enemies when I make them my friends. Instead of wondering when your next vacation is, maybe you should set up a life you                 ');
INSERT INTO `news` VALUES (86, 'The Main Window consists of several toolbars and panes                ', 'Yue Fu Shing', '2000-09-03', 'SQL Editor allows you to create and edit SQL text, prepare and execute selected queries. Typically, it is employed as an encrypted version of Telnet.');
INSERT INTO `news` VALUES (87, 'Monitored servers include MySQL, MariaDB and SQL Server,              ', 'Carol Jackson', '2012-05-01', 'The Navigation pane employs tree structure which allows you to take action upon the database and their objects through their pop-up                   ');
INSERT INTO `news` VALUES (88, 'Navicat authorizes you to make connection to remote                   ', 'Cheng Chun Yu', '2003-04-22', 'With its well-designed Graphical User Interface(GUI), Navicat lets you quickly and easily create, organize, access and share information              ');
INSERT INTO `news` VALUES (89, 'Champions keep playing until they get it right.', 'Shimizu Mitsuki', '2019-09-06', 'It provides strong authentication and secure encrypted communications between two hosts, known as SSH Port Forwarding (Tunneling),                    ');
INSERT INTO `news` VALUES (90, 'Success consists of going from failure to failure without             ', 'Jean Owens', '2007-07-07', 'SQL Editor allows you to create and edit SQL text, prepare and execute selected queries. Champions keep playing until they get it right.              ');
INSERT INTO `news` VALUES (91, 'If your Internet Service Provider (ISP) does not provide              ', 'Kwong Suk Yee', '2006-07-17', 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your connection settings, queries,                  ');
INSERT INTO `news` VALUES (92, 'Secure Sockets Layer(SSL) is a protocol for transmitting              ', 'Ti Tak Wah', '2008-09-14', 'Navicat Data Modeler enables you to build high-quality conceptual, logical and physical data models for a wide variety of audiences.');
INSERT INTO `news` VALUES (93, 'Monitored servers include MySQL, MariaDB and SQL Server,              ', 'Choi Tin Wing', '2003-08-11', 'Remember that failure is an event, not a person. The past has no power over the present moment. You can select any connections, objects               ');
INSERT INTO `news` VALUES (94, 'SQL Editor allows you to create and edit SQL text,                    ', 'He Xiaoming', '2011-02-10', 'Export Wizard allows you to export data from tables, collections, views, or query results to any available formats. Flexible settings                 ');
INSERT INTO `news` VALUES (95, 'You will succeed because most people are lazy.', 'Douglas Sanchez', '2009-04-23', 'Remember that failure is an event, not a person. You will succeed because most people are lazy.');
INSERT INTO `news` VALUES (96, 'SSH serves to prevent such vulnerabilities and allows                 ', 'Philip Hayes', '2016-04-25', 'The On Startup feature allows you to control what tabs appear when you launch Navicat.');
INSERT INTO `news` VALUES (97, 'It is used while your ISPs do not allow direct connections,           ', 'Yamamoto Hazuki', '2002-05-28', 'The Information Pane shows the detailed object information, project activities, the DDL of database objects, object dependencies, membership          ');
INSERT INTO `news` VALUES (98, 'To clear or reload various internal caches, flush tables,             ', 'Dawn Green', '2015-10-21', 'You will succeed because most people are lazy. How we spend our days is, of course, how we spend our lives. After logged in the Navicat               ');
INSERT INTO `news` VALUES (99, 'Navicat Data Modeler is a powerful and cost-effective                 ', 'Jeffrey Sullivan', '2004-04-23', 'I may not have gone where I intended to go, but I think I have ended up where I needed to be. Typically, it is employed as an encrypted               ');
INSERT INTO `news` VALUES (100, 'In the middle of winter I at last discovered that there               ', 'Lin Yunxi', '2005-09-20', 'It provides strong authentication and secure encrypted communications between two hosts, known as SSH Port Forwarding (Tunneling),                    ');

-- ----------------------------
-- Table structure for types
-- ----------------------------
DROP TABLE IF EXISTS `types`;
CREATE TABLE `types`  (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `type` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 21 CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of types
-- ----------------------------
INSERT INTO `types` VALUES (1, '科幻');
INSERT INTO `types` VALUES (2, '战争');
INSERT INTO `types` VALUES (3, '历史');
INSERT INTO `types` VALUES (4, '动作');
INSERT INTO `types` VALUES (5, '爱情');
INSERT INTO `types` VALUES (6, '喜剧');
INSERT INTO `types` VALUES (7, '冒险');
INSERT INTO `types` VALUES (8, '恐怖');
INSERT INTO `types` VALUES (9, '动作');
INSERT INTO `types` VALUES (10, '高兴');
INSERT INTO `types` VALUES (22, '测试');

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `username` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '用户名',
  `password` varchar(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '密码',
  `phone` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '电话',
  `email` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '邮箱',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 31 CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', NULL, NULL);
INSERT INTO `user` VALUES (27, '123', '202cb962ac59075b964b07152d234b70', '1233232', '2426481498@qq.com');
INSERT INTO `user` VALUES (28, '1234', '202cb962ac59075b964b07152d234b70', '128', '2426481498@qq.com');
INSERT INTO `user` VALUES (29, '1234156', '8164a6bff4e18648bbff78fc4f7709c5', '1234156', '2426481498@qq.com');
INSERT INTO `user` VALUES (30, '12345', '827ccb0eea8a706c4c34a16891f84e7b', '12345', '2426481498@qq.com');
INSERT INTO `user` VALUES (31, '42812052', '59644088', '5052-7812', 'stephenma6@icloud.com');
INSERT INTO `user` VALUES (32, '28679873', '04596738', '74-304-9751', 'brvincent1@mail.com');
INSERT INTO `user` VALUES (33, '56234750', '9787766179249', '5582 100533', 'joe@icloud.com');
INSERT INTO `user` VALUES (34, '30313725', '836854650548', '52-007-3904', 'aayano@mail.com');
INSERT INTO `user` VALUES (35, '78881928', '07620928', '7628 958442', 'hiutung223@gmail.com');
INSERT INTO `user` VALUES (36, '42044829', '04499985', '7864 645793', 'shazhiyuan@icloud.com');
INSERT INTO `user` VALUES (37, '56778313', '84974082', '7039 234119', 'nakamura10@mail.com');
INSERT INTO `user` VALUES (38, '44045040', '443058332387', '(20) 6687 5342', 'rui6@gmail.com');
INSERT INTO `user` VALUES (39, '73809596', '2017830563863', '193-9092-0278', 'ywf@gmail.com');
INSERT INTO `user` VALUES (40, '72947187', 'IJH-9705', '(161) 876 6591', 'lanhu@outlook.com');
INSERT INTO `user` VALUES (41, '29901343', '9788776881993', '(151) 088 9959', 'xiaomen6@yahoo.com');
INSERT INTO `user` VALUES (42, '20395566', 'VDJ-3409', '(1865) 09 2730', 'kwokkuen1970@gmail.com');
INSERT INTO `user` VALUES (43, '51335754', '00305648', '21-6210-7970', 'sasrin@icloud.com');
INSERT INTO `user` VALUES (44, '69049298', '7382995566536', '7317-0418', 'morita07@yahoo.com');
INSERT INTO `user` VALUES (45, '28112105', '9799457101507', '7236-9696', 'minatomatsu74@icloud.com');
INSERT INTO `user` VALUES (46, '18506013', '0748323148015', '80-5191-6219', 'yuecw430@yahoo.com');
INSERT INTO `user` VALUES (47, '43059698', '195568340221', '5516 339914', 'chin7@outlook.com');
INSERT INTO `user` VALUES (48, '776824', '431142263099', '66-780-9022', 'joclark01@outlook.com');
INSERT INTO `user` VALUES (49, '43165246', '0305432616899', '28-706-5834', 'otayuto@hotmail.com');
INSERT INTO `user` VALUES (50, '23820152', '13967857', '5749 739698', 'yunfat4@outlook.com');
INSERT INTO `user` VALUES (51, '123454244', '202cb962ac59075b964b07152d234b70', '23', '2426481498@qq.com');
INSERT INTO `user` VALUES (52, 'test2', '202cb962ac59075b964b07152d234b70', '1234562', '2426481497@qq.com');

SET FOREIGN_KEY_CHECKS = 1;
